### PR TITLE
Release 0.6.1

### PR DESCRIPTION
**Pull request by cgwalters**
build: Use released oci-spec

See https://github.com/containers/oci-spec-rs/pull/94

---

lib: Bump rustix and cap-std-ext

cap-std-ext needs the latest rustix.

---

Release 0.6.1

I believe this is all semver compat; we have a big change queued
up for the layer split work which should come after this.

---

### CODE REVIEW

**Comment by lucab** [comment]
If possible, it would be good to sneak https://github.com/ostreedev/ostree-rs-ext/pull/220 in before the release, so that exported tar artifacts are a bit less broken.

**Comment by cgwalters** [comment]
Yeah, it's also time to transfer cap-std-ext to coreos/ and have it require peer review I think.

**Comment by cgwalters** [comment]
OK, respun with https://crates.io/crates/cap-std-ext/0.23.0

**Review by lucab — APPROVED** [review]

**Comment by lucab** [comment]
@cgwalters ugh sorry, feel to just revert it for now and release without that. I'll land better logic after that release.

**Pull request merged**
