### PR TITLE
Support for split layers

### PR DESCRIPTION
**Pull request by cgwalters**
Support for split layers

Closes: https://github.com/ostreedev/ostree-rs-ext/issues/69

This is initial basic support for splitting files (objects) from
a commit into separate container image layers, and reassembling
those layers into a commit on the client.

We retain our present logic around e.g. GPG signature verification.

There's a new `chunking.rs` file which has logic to automatically
factor out things like the kernel/initramfs and large files.

In order to fetch these images client side, we now heavily
intermix/cross the previous code for fetching non-ostree layers.

---

### CODE REVIEW

**Comment by cgwalters** [comment]
OK, this is finally in a state where it seems to work!  Lifting draft, but it's a huge change so we need careful review and thought.  At least the core logic today is only opt-in, you have to `ostree container encapsulate --ex-chunked ...` to enable it.

**Comment by cgwalters** [comment]
Also to make use of this you need a skopeo with https://github.com/containers/skopeo/pull/1523 which isn't released yet - I pinged about that.

**Comment by cgwalters** [comment]
OK now with https://github.com/ostreedev/ostree-rs-ext/pull/268 this is getting closer to ready to merge I think!

**Comment by cgwalters** [comment]
This does still block on https://bodhi.fedoraproject.org/updates/FEDORA-2022-be638496e5 and...hmm, https://gitlab.com/redhat/centos-stream/rpms/skopeo/-/commit/e3b85c5431074f8ed2944f570d45803961c0a068 landed but I don't see it in C9S yet.  Oh...perhaps because https://bugzilla.redhat.com/show_bug.cgi?id=2000051 isn't marked VERIFIED or something?

**Comment by cgwalters** [comment]
OK, CI on https://github.com/coreos/rpm-ostree/pull/3478 is passing!  I'd like to merge this now, I've fixed the bugs that caused it break the current v0 container format, so while it's a lot of new code, I think the risk is pretty low because most of the new bits are opt-in.

**Review by jlebon — APPROVED** [review]
Very cool! I've only skimmed this, but it looks sane overall.

**Review by jmarrero — APPROVED** [review]

**Pull request merged**
