### PR TITLE
container: Fix idempotency of config defaults merging

### PR DESCRIPTION
**Pull request by cgwalters**
In rpm-ostree we provide a custom config to override the isolation user, calling the merge function.  But the logic for idempotency of auth handling was buggy - it needed to consider having `auth_data` already specified.

### CODE REVIEW

**Comment by jmarrero** [comment]
Even with the CI failure adding this patch make privileged pulls work again.

**Comment by cgwalters** [comment]
That CI failure was a network flake, restarted it.

**Comment by cgwalters** [comment]
> Even with the CI failure adding this patch make privileged pulls work again.

Can you officially stamp the PR as approved?

**Review by jmarrero — APPROVED** [review]
lgtm

**Pull request merged**
