### PR TITLE
Handle long and denormal symlinks

### PR DESCRIPTION
**Pull request by cgwalters**
Use new `append_link()` API to handle long symlinks

I hit this when exporting Fedora Silverblue, there are some
long symlinks in there.

Depends: https://github.com/alexcrichton/tar-rs/pull/273
Closes: https://github.com/ostreedev/ostree-rs-ext/issues/162

---

tar/export: Write symlink targets literally

Requires: https://github.com/alexcrichton/tar-rs/pull/274

And I'll just copy/paste the commit message from there, lightly edited:

In https://github.com/ostreedev/ostree we generate a cryptographic
checksum over files and symlinks, and directories.

ostree does not currently perform any canonicalization on symlinks;
we'll respect and honor whatever bytes we're provided as input,
and replicate that on the target.

We're using the Rust tar crate to do tar serialization,
which has so far worked fine...except, I hit this corner case:

```
[root@cosa-devsh ~]# rpm -qf /usr/lib/systemd/systemd-sysv-install
chkconfig-1.13-2.el8.x86_64
[root@cosa-devsh ~]# ll /usr/lib/systemd/systemd-sysv-install
lrwxrwxrwx. 2 root root 24 Nov 29 18:08 /usr/lib/systemd/systemd-sysv-install -> ../../..//sbin/chkconfig
[root@cosa-devsh ~]#
```

But, using `set_link_name` to write the tarball, we end up with
the canonicalized path `../../../sbin/chkconfig` - i.e. without the
double `//`.  This breaks the checksum.

Now, I am a bit tempted to change ostree to do canonicalization.  But
even if we did, I'd need to *exactly* match what tar-rs is doing.

(I may of course also try to change the rhel8 systemd package, but
 that's going to take a while to propagate and this corner case isn't
 the only one I'm sure)

---

### CODE REVIEW

**Comment by cgwalters** [comment]
OK there's a new [tar 0.4.38](https://crates.io/crates/tar/0.4.38) with my PRs!  Because it conflicted, I'm rolling
https://github.com/ostreedev/ostree-rs-ext/pull/182
into this one.

(And now that I look at this...honestly I regret not also adding `append_link_literal`.  Oops.)

**Review by jmarrero — APPROVED** [review]
lgtm

**Comment by JayDoubleu** [comment]
I'm getting the same error with below: 
```
rpm-ostree ex-container encapsulate --repo=repo fedora/35/x86_64/silverblue docker://ghcr.io/JayDoubleu/fedora-silverblue:35
error: Building oci: Writing ostree root to blob: Exporting commit: provided value is too long when setting link name for 
```
```
[jaydoubleu@thinkxps-sb workstation-ostree-config]$ rpm-ostree --version
rpm-ostree:
 Version: '2021.14'
 Git: 5cb5980ad94eaaee0585b8dde1a733cb12670b19
 Features:
  - compose
  - rust
  - fedora-integration
```

Does it mean I should wait for newer rpm-ostree ?

**Comment by cgwalters** [comment]
Hi, yes - this fix should land in the next rpm-ostree release.  There are automated builds from git main at https://copr.fedorainfracloud.org/coprs/g/CoreOS/continuous/

You can also build from source of course.

**Pull request merged**
