### PR TITLE
readme: fix the broken container/store docs.rs url

### PR DESCRIPTION
**Pull request by juhp**

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
Thanks!

**Comment by cgwalters** [comment]
Hm, GH actions went out to lunch or so, trying a close/reopen cycle.

**Comment by juhp** [comment]
Sure thanks
(I was trying to `skip ci` but maybe that doesn't work for PRs or I put it in the wrong place..?)

**Review by cgwalters — APPROVED** [review]

**Comment by cgwalters** [comment]
OK https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork shows a button to click, but I am not seeing it.

**Comment by cgwalters** [comment]
OK @lucab figured it out, it's because your commit message has `[skip ci]` (per [this blog](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)) but our merge flow requires a CI run right now.

**Comment by cgwalters** [comment]
Would you mind re-pushing without that bit?  The test here isn't too expensive and is pretty reliable.

I *can* temporarily uncheck the "enforce status checks for administrators" box but I'd prefer not to.

**Comment by cgwalters** [comment]
> Would you mind re-pushing without that bit?

(nevermind, I did it)

**Comment by juhp** [comment]
Thanks

**Pull request merged**
