### PR TITLE
lib: Drop gvariant_utils module

### PR DESCRIPTION
**Pull request by cgwalters**
We can now reuse the main GLib 0.14 code since we have the
binding for `g_variant_get_normal_form()`.

### CODE REVIEW

**Comment by cgwalters** [comment]
This will depend on both a new ostree and glib version.

**Comment by cgwalters** [comment]
Soft requires https://github.com/ostreedev/ostree-rs/pull/26

**Comment by cgwalters** [comment]
Lifting draft since https://crates.io/crates/glib/0.14.4 is out!

**Review by jlebon — APPROVED** [review]
Nice!

**Pull request merged**
